name: CI

on: pull_request

jobs:
  build-frontend:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'frontend') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock

      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yarn build

  lint-frontend:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'frontend') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format
        
  lint-backend:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'backend') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: skkuse-team7
          environment-file: env.yaml
          python-version: 3.10
          auto-activate-base: false

      - name: Lint
        run: flake8
